name: Push to Docker Hub
on:
  push:
    branches: [master]
jobs:
  thuchienpush:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: login docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}