name: Push to Docker Hub
on:
  push:
    branches: [main]
jobs:
  thuchienpush:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: login docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Build and push
        uses: docker/build-push-action@v2.10.0
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-push
      -
        name: verify
        run: echo ${{steps.docker_build.outputs.digest}}
